{application,herlon,
             [{description,"Easy-to-use TOTP server"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{herlon,[]}},
              {env,[]},
              {modules,[herlon,herlon_internal,herlon_oath_worker,
                        herlon_qr_worker,herlon_rest_check,herlon_rest_get_qr,
                        herlon_rest_qr,herlon_sup]}]}.
